const Homeproduct =
[
    {
        id: 1,
        Name: 'Kurtis set',
        image: 'website/src/assets/image/p-1.jpg',
        price: '20',
        cat: 'Kurtis set',
        type: 'new',
    },
    {
        id: 2,
        Name: 'Kurti',
        image: 'website/src/assets/image/p-2.jpg',
        price: '10',
        cat: 'Tops',
        type: 'new',
    },
    {
        id: 3,
        Name: 'Black jean',
        image: 'website/src/assets/image/p-3.jpg',
        price: '65',
        cat: 'Jean',
        type: 'new',
    },
    {
        id: 4,
        Name: 'Green Saree',
        image: 'website/src/assets/image/p-4.jpg',
        price: '95',
        cat: 'Saree',
        type: 'top',
    },
    {
        id: 5,
        Name: 'Short top',
        image: 'website/src/assets/image/p-5.jpg',
        price: '82',
        cat: 'Short top',
        type: 'top',
    },
    {
        id: 6,
        Name: 'Blue saree',
        image: 'website/src/assets/image/p-6.jpg',
        price: '12',
        cat: 'Saree',
        type: 'top',
    },
    {
        id: 7,
        Name: 'Jean',
        image: 'website/src/assets/image/p-7.jpg',
        price: '76',
        cat: 'Jean',
        type: 'new',
    },
    {
        id: 8,
        Name: 'Short top',
        image: 'website/src/assets/image/p-8.jpg',
        price: '45',
        cat: 'Short top',
        type: 'top',
    },
    {
        id: 9,
        Name: 'Kurti',
        image: 'website/src/assets/image/p-9.jpg',
        price: '34',
        cat: 'Tops',
        type: 'featured',
    },
    {
        id: 10,
        Name: 'kurti',
        image: 'website/src/assets/image/p-10.jpg',
        price: '90',
        cat: 'Tops',
        type: 'featured',
    },
    {
        id: 11,
        Name: 'Short top',
        image: 'website/src/assets/image/p-11.jpg',
        price: '21',
        cat: 'Short top',
        type: 'featured',
    },
    {
        id: 12,
        Name: 'kurti',
        image: 'website/src/assets/image/p-12.jpg',
        price: '32',
        cat: 'Tops',
        type: 'featured',
    }
]

export default Homeproduct